name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  S3_BUCKET_NAME: heyhi-deploy
  JASYPT_ENCRYPTOR_KEY: ${{ secrets.JASYPT_ENCRYPTOR_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0

      - name: Give exec permissions to gradlew script
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
    
      - name: Make directory
        run: mkdir -p deploy

      - name: Copy .jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Compress /deploy
        run: zip -r ./heyhi.zip ./deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::048045876961:user/my-github-actions-iam
          role-session-name: 'tester'
          aws-region: ap-northeast-2

      - name: Uplaod to S3
        run: aws s3 cp --region ap-northeast-2 ./heyhi.zip s3://S3_BUCKET_NAME/heyhi.zip
        
