name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  S3_BUCKET_NAME: heyhi-deploy
  JASYPT_ENCRYPTOR_KEY: ${{ secrets.JASYPT_ENCRYPTOR_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0

      - name: Give exec permissions to gradlew script
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
    
      
