name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  S3_BUCKET_NAME: heyhi-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySql
        uses: mirrormutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          mysql database: heyhello
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Give exec permissions to gradlew script
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
    
      
